source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

use_frameworks!

target 'ConfigKit_Example' do
  pod 'LYConfigKit', :path => '../'
  
  # pod 'SVProgressHUD', '~> 2.0.3'

  target 'ConfigKit_Tests' do
    inherit! :search_paths

    
  end
end
